# Generated by Django 4.2.4 on 2023-08-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_books"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Autor", "verbose_name_plural": "Autores"},
        ),
        migrations.AlterModelOptions(
            name="books",
            options={"verbose_name": "Livro"},
        ),
        migrations.AlterModelOptions(
            name="gender",
            options={"verbose_name": "Genero"},
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="books",
            name="description",
            field=models.TextField(verbose_name="Descrição do livro"),
        ),
        migrations.AlterField(
            model_name="gender",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="Nome"),
        ),
    ]
