# Generated by Django 4.2.4 on 2023-08-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_alter_author_options_alter_books_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gender",
            name="squad",
            field=models.CharField(
                default="Joga Junto", max_length=30, verbose_name="Squad"
            ),
        ),
        migrations.AlterField(
            model_name="gender",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nome"),
        ),
        migrations.AlterUniqueTogether(
            name="gender",
            unique_together={("name", "squad")},
        ),
    ]
